[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scientex_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.46.0",
]

[project.scripts]
scientex_agent = "scientex_agent.cli:main"

[tool.uv]
package = true
